
robot_cfg:
  kinematics:
    use_usd_kinematics: False
    # isaac_usd_path: "/Isaac/Robots/Franka/franka.usd"
    # usd_path: "robot/non_shipping/franka/franka_panda_meters.usda"
    # usd_robot_root: "/panda"
    # usd_flip_joints: ["panda_joint1","panda_joint2","panda_joint3","panda_joint4", "panda_joint5",
    #   "panda_joint6","panda_joint7","panda_finger_joint1", "panda_finger_joint2"]
    # usd_flip_joints: {
    # "panda_joint1": "Z",
    # "panda_joint2": "Z",
    # "panda_joint3": "Z",
    # "panda_joint4": "Z",
    #  "panda_joint5": "Z",
    # "panda_joint6": "Z",
    # "panda_joint7": "Z",
    # "panda_finger_joint1": "Y",
    #  "panda_finger_joint2":  "Y",
    # }
    
    # usd_flip_joint_limits: ["panda_finger_joint2"]
    urdf_path: "robot/franka_description/triple_franka.urdf"
    asset_root_path: "robot/franka_description"
    # 
    # base_link: "panda_link0"
    base_link: "base_fixture_link"
    ee_link: "panda_hand"
    link_names: ["panda2_hand","panda3_hand"]
    collision_link_names:
      [
        "panda_link0",
        "panda_link1",
        "panda_link2",
        "panda_link3",
        "panda_link4",
        "panda_link5",
        "panda_link6",
        "panda_link7",
        "panda_hand",
        "panda_leftfinger",
        "panda_rightfinger",

        "panda2_link0",
        "panda2_link1",
        "panda2_link2",
        "panda2_link3",
        "panda2_link4",
        "panda2_link5",
        "panda2_link6",
        "panda2_link7",
        "panda2_hand",
        "panda2_leftfinger",
        "panda2_rightfinger",

        "panda3_link0",
        "panda3_link1",
        "panda3_link2",
        "panda3_link3",
        "panda3_link4",
        "panda3_link5",
        "panda3_link6",
        "panda3_link7",
        "panda3_hand",
        "panda3_leftfinger",
        "panda3_rightfinger",
       
      ]
    collision_spheres: "spheres/triple_franka_mesh.yml"
    collision_sphere_buffer: 0.0025 # 0.0025
    # extra_collision_spheres: {"": 4,"2": 4}
    # use_global_cumul: True
    self_collision_ignore:
      {
        "panda_link0": ["panda_link1", "panda_link2"],
        "panda_link1": ["panda_link2", "panda_link3", "panda_link4"],
        "panda_link2": ["panda_link3", "panda_link4"],
        "panda_link3": ["panda_link4", "panda_link6"],
        "panda_link4":["panda_link5", "panda_link6", "panda_link7", "panda_link8"],
        "panda_link5": ["panda_link6", "panda_link7", "panda_hand","panda_leftfinger", "panda_rightfinger"],
        "panda_link6": ["panda_link7", "panda_hand", "panda_leftfinger", "panda_rightfinger"],
        "panda_link7": ["panda_hand",  "panda_leftfinger", "panda_rightfinger"],
        "panda_hand": ["panda_leftfinger", "panda_rightfinger"],
        "panda_leftfinger": ["panda_rightfinger"],
      
        "panda2_link0": ["panda2_link1", "panda2_link2"],
        "panda2_link1": ["panda2_link2", "panda2_link3", "panda2_link4"],
        "panda2_link2": ["panda2_link3", "panda2_link4"],
        "panda2_link3": ["panda2_link4", "panda2_link6"],
        "panda2_link4":["panda2_link5", "panda2_link6", "panda2_link7", "panda2_link8"],
        "panda2_link5": ["panda2_link6", "panda2_link7", "panda2_hand","panda2_leftfinger", "panda2_rightfinger"],
        "panda2_link6": ["panda2_link7", "panda2_hand", "panda2_leftfinger", "panda2_rightfinger"],
        "panda2_link7": ["panda2_hand", "panda2_leftfinger", "panda2_rightfinger"],
        "panda2_hand": ["panda2_leftfinger", "panda2_rightfinger"],
        "panda2_leftfinger": ["panda2_rightfinger"],

        "panda3_link0": ["panda3_link1", "panda3_link2"],
        "panda3_link1": ["panda3_link2", "panda3_link3", "panda3_link4"],
        "panda3_link2": ["panda3_link3", "panda3_link4"],
        "panda3_link3": ["panda3_link4", "panda3_link6"],
        "panda3_link4":["panda3_link5", "panda3_link6", "panda3_link7", "panda3_link8"],
        "panda3_link5": ["panda3_link6", "panda3_link7", "panda3_hand","panda3_leftfinger", "panda3_rightfinger"],
        "panda3_link6": ["panda3_link7", "panda3_hand", "panda3_leftfinger", "panda3_rightfinger"],
        "panda3_link7": ["panda3_hand", "panda3_leftfinger", "panda3_rightfinger"],
        "panda3_hand": ["panda3_leftfinger", "panda3_rightfinger"],
        "panda3_leftfinger": ["panda3_rightfinger"],
      
        
      }
    
    self_collision_buffer:
      {
        "panda_link0": 0.05, 
        "panda_link1": 0.05,
        "panda_link2": 0.05,
      }
    #link_names: ["panda_link4"]
    lock_joints: null
    mesh_link_names:
      [
        "panda_link0",
        "panda_link1",
        "panda_link2",
        "panda_link3",
        "panda_link4",
        "panda_link5",
        "panda_link6",
        "panda_link7",
        "panda_hand",
        "panda_leftfinger",
        "panda_rightfinger",

        "panda2_link0",
        "panda2_link1",
        "panda2_link2",
        "panda2_link3",
        "panda2_link4",
        "panda2_link5",
        "panda2_link6",
        "panda2_link7",
        "panda2_hand",
        "panda2_leftfinger",
        "panda2_rightfinger",

        "panda3_link0",
        "panda3_link1",
        "panda3_link2",
        "panda3_link3",
        "panda3_link4",
        "panda3_link5",
        "panda3_link6",
        "panda3_link7",
        "panda3_hand",
        "panda3_leftfinger",
        "panda3_rightfinger",
      ]
    # lock_joints: {"panda_finger_joint1": 0.04, "panda_finger_joint2": 0.04}
    # extra_links: {"":{"parent_link_name": "panda_hand" , 
    # "link_name": "", "fixed_transform": [0,0,0,1,0,0,0], "joint_type":"FIXED",
    # "joint_name": "attach_joint" }}

    cspace:
      joint_names: [
      "panda_joint1","panda_joint2","panda_joint3","panda_joint4", "panda_joint5",
      "panda_joint6","panda_joint7","panda_finger_joint1", "panda_finger_joint2",

      "panda2_joint1","panda2_joint2","panda2_joint3","panda2_joint4", "panda2_joint5",
      "panda2_joint6","panda2_joint7","panda2_finger_joint1", "panda2_finger_joint2",

      "panda3_joint1","panda3_joint2","panda3_joint3","panda3_joint4", "panda3_joint5",
      "panda3_joint6","panda3_joint7","panda3_finger_joint1", "panda3_finger_joint2"
      ]
      retract_config: [0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04
                      ,0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04
                      ,0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.04, 0.04]
      null_space_weight: [1,1,1,1,1,1,1,1,1,
                          1,1,1,1,1,1,1,1,1,
                          1,1,1,1,1,1,1,1,1]
      cspace_distance_weight: [1,1,1,1,1,1,1,1,1,
                              1,1,1,1,1,1,1,1,1,
                              1,1,1,1,1,1,1,1,1]

      max_acceleration: 15.0
      max_jerk: 500.0